{
 "title": "CROMA Bike Garage",
 "tags": [ "CROMA" ],
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "timeRange",
    "query": "Today : 0d, Yesterday : 1d, The day before yesterday : 2d, 3 days ago : 3d, 4 days ago : 4d, 5 days ago : 5d, 6 days ago : 6d, A week ago : 7d"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# CROMA & LAMA Bike Garage \nThis dashboard shows all the information relatives to the bicycle garage, \nnext to the Croma and Lama's laboratoria. The panel _**Today's opened doors**_ \ndisplays the number of time the garage's door opens during the current day. \nThe period of the graphs is not adjustable."
   }
  },
  {
   "title": "Opened doors' evolution ",
   "type": "barchart",
   "description": "Number of opened doors during the currrent day",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "import \"experimental\"\r\nimport \"date\"\r\n\r\nfrom(bucket: \"sacha\")\r\n  |> range(start: experimental.addDuration(d: 5h, to: date.sub(from:today(), d:${timeRange})), stop: experimental.addDuration(d: 20h, to: date.sub(from:today(), d:${timeRange})))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"deviceName\"] == \"porte-garage-velo\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DoorWindow_Event\")\r\n  |> filter(fn: (r) => r[\"batiment\"] == \"garage-velo\")\r\n  |> aggregateWindow(every: 30m, fn: count, createEmpty: true)\r\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "Opened doors ${timeRange}",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"experimental\"\r\nimport \"date\"\r\n\r\nstartRequest = date.sub(from:today(), d:${timeRange})\r\n\r\nfrom(bucket: \"sacha\")\r\n  |> range(start: startRequest, stop: date.add(to:startRequest, d:1d))\r\n  |> filter(fn: (r) => r[\"batiment\"] == \"garage-velo\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DoorWindow_Event\")\r\n  |> count(column: \"_value\")\r\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Number of bikes stored",
   "type": "barchart",
   "description": "Compare the number of stored bikes evolution between the current week and last week",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"experimental/date/boundaries\"\r\nimport \"math\"\r\n\r\nweekDays = [\"Sunday\", \"Monday\", \"Tuesday\", \"Wednesday\", \"Thursday\", \"Friday\", \"Saturday\"]\r\n\r\nstartWeek = boundaries.week(week_offset:-1).start\r\nendWeek = boundaries.week().stop\r\n\r\nfrom(bucket: \"sacha\")\r\n  |> range(start: startWeek, stop: endWeek)\r\n  |> filter(fn: (r) => r[\"batiment\"] == \"garage-velo\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DoorWindow_Event\")\r\n  |> filter(fn: (r) => r[\"_value\"] == \"Open\")\r\n  |> aggregateWindow(every: 1d, offset: 0s, timeSrc: \"_start\", fn: count, createEmpty: true)\r\n  |> map(fn: (r) => ({r with dayOfWeek: weekDays[date.weekDay(t: r._time)]}))\r\n  |> map(fn: (r) => ({ r with nbBikes: math.floor(x:float(v: r._value + 1) * 0.5) }))\r\n  |> map(fn: (r) => ({r with week: \"week \" + string(v: date.week(t: r._time))}))\r\n  |> timeShift(duration: 1d)\r\n  |> pivot(rowKey: [\"dayOfWeek\"], columnKey: [\"week\"], valueColumn: \"nbBikes\")\r\n  |> drop(columns: [\"_field\", \"_start\", \"_stop\", \"batiment\", \"applicationName\", \"devEui\", \"deviceName\", \"host\", \"name\", \"site\", \"_measurement\", \"_time\", \"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "Number of opened doors and bikes stored this month",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"experimental/date/boundaries\"\r\nimport \"math\"\r\n\r\nfrom(bucket: \"sacha\")\r\n  |> range(start: boundaries.month().start, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"batiment\"] == \"garage-velo\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DoorWindow_Event\")\r\n  |> count(column: \"_value\")\r\n  |> map(fn: (r) => ({r with nbBikes: math.floor(x:float(v: r._value + 1) * 0.5)}))\r\n  |> drop(columns: [\"_field\", \"_start\", \"_stop\", \"applicationName\", \"batiment\", \"site\", \"salle\", \"devEui\", \"deviceName\", \"host\"])\r\n  |> yield(name: \"sum\")\r\n"
    }
   ]
  },
  {
   "title": "Stored bikes",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"experimental/date/boundaries\"\r\nimport \"math\"\r\n\r\nweekDays = [\"Sunday\", \"Monday\", \"Tuesday\", \"Wednesday\", \"Thursday\", \"Friday\", \"Saturday\"]\r\nmonths = [\"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\", \"August\", \"September\", \"October\", \"November\", \"December\"]\r\n\r\nfrom(bucket: \"sacha\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"batiment\"] == \"garage-velo\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DoorWindow_Event\")\r\n  |> filter(fn: (r) => r[\"_value\"] == \"Open\")\r\n  |> aggregateWindow(every: 1w, offset: -3d, timeSrc: \"_start\", fn: count, createEmpty: true)\r\n  |> map(fn: (r) => ({ r with nbBikes: math.floor(x:float(v: r._value + 1) * 0.5) }))\r\n  //|> map(fn: (r) => ({r with week: \"week \" + string(v: date.week(t: date.add(d: 3d, to: r._time)))}))\r\n  //|> map(fn: (r) => ({r with month:  months[date.month(t: r._time) - 1]}))\r\n  |> drop(columns: [\"_field\", \"_start\", \"_stop\", \"batiment\", \"applicationName\", \"devEui\", \"deviceName\", \"host\", \"name\", \"site\", \"_measurement\", \"_value\"])\r\n"
    }
   ]
  }
 ]
}