{
 "title": "Température et humidité DEV",
 "tags": [
  "LHT65",
  "Temperature",
  "Humidity",
  "Generated"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10m",
 "templating": {
  "list": [
   {
    "name": "MEASUREMENT",
    "query": "Temperature : TempC_SHT,Humidity : Hum_SHT,Air Quality : Co2_SHT"
   },
   {
    "name": "CAMPUS",
    "query": "import \"influxdata/influxdb/schema\"\r\nimport \"strings\"\r\nimport \"array\"\r\n \r\nsites = schema.tagValues(\r\n  bucket: \"iot-platform\",\r\n  tag: \"site\",\r\n  predicate: (r) => r._field == \"${MEASUREMENT}\",\r\n  start: v.timeRangeStart\r\n)\r\n|> map(fn: (r) => ({ r with site: strings.toLower(v: r._value) }))\r\n|> distinct(column: \"site\")\r\n\r\ndefault = array.from(rows: [{\"_value\": \"none\"}])\r\n\r\nunion(tables: [sites, default])\r\n"
   },
   {
    "name": "BATIMENT",
    "query": "import \"influxdata/influxdb/schema\"\r\nimport \"strings\"\r\nimport \"array\"\r\n\r\nbuildings = schema.tagValues(\r\n  bucket: \"iot-platform\",\r\n  tag: \"batiment\",\r\n  predicate: (r) => r._field == \"${MEASUREMENT}\"\r\n    and exists r[\"site\"]\r\n    and contains(value: strings.toLower(v:r[\"site\"]), set: ${CAMPUS:json}),\r\n  start: v.timeRangeStart\r\n)\r\n|> map(fn: (r) => ({ r with building: strings.toLower(v: r._value) }))\r\n|> distinct(column: \"building\")\r\n\r\ndefault = array.from(rows: [{\"_value\": \"none\"}])\r\n\r\nunion(tables: [buildings, default])"
   },
   {
    "name": "ROOM",
    "query": "import \"influxdata/influxdb/schema\"\r\nimport \"strings\"\r\nimport \"array\"\r\n\r\nrooms = schema.tagValues(\r\n  bucket: \"iot-platform\",\r\n  tag: \"salle\",\r\n  predicate: (r) => \r\n    r._field == \"${MEASUREMENT}\"\r\n    and exists r[\"site\"]\r\n    and exists r[\"batiment\"]\r\n    and contains(value: strings.toLower(v: r[\"site\"]), set: ${CAMPUS:json}) \r\n    and contains(value: strings.toLower(v: r[\"batiment\"]), set: ${BATIMENT:json}),\r\n  start: v.timeRangeStart\r\n)\r\n|> map(fn: (r) => ({ r with room: strings.toLower(v: r._value) }))\r\n|> distinct(column: \"room\")\r\n\r\ndefault = array.from(rows: [{\"_value\": \"none\"}])\r\n\r\nunion(tables: [rooms, default])\r\n"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Temperature and Humidity in developpment\nTemperature and humidity data caught by LHT65 sensors at Technolac Campus.\n\nThis is an automatically generated dashboard."
   }
  },
  {
   "title": "${MEASUREMENT} of ${ROOM}",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 3 },
   "repeat": "MEASUREMENT",
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"iot-platform\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${MEASUREMENT}\" and \"${MEASUREMENT}\" == \"TempC_SHT\")\r\n  |> filter(fn: (r) => exists r[\"site\"] and contains(set: ${CAMPUS:json}, value: strings.toLower(v: r[\"site\"])))\r\n  |> filter(fn: (r) => (exists r[\"batiment\"] and contains(set: ${BATIMENT:json}, value: strings.toLower(v: r[\"batiment\"]))) or\r\n    (exists r[\"building\"] and contains(set: ${BATIMENT:json}, value: strings.toLower(v: r[\"building\"]))))\r\n  |> filter(fn: (r) => (exists r[\"salle\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"salle\"]))) or\r\n    (exists r[\"room\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"room\"]))))\r\n  |> keep(columns: [\"_value\", \"_time\", \"batiment\", \"salle\", \"site\"])  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n"
    },
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"iot-platform\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${MEASUREMENT}\" and \"${MEASUREMENT}\" == \"Hum_SHT\")\r\n  |> filter(fn: (r) => exists r[\"site\"] and contains(set: ${CAMPUS:json}, value: strings.toLower(v: r[\"site\"])))\r\n  |> filter(fn: (r) => (exists r[\"batiment\"] and contains(set: ${BATIMENT:json}, value: strings.toLower(v: r[\"batiment\"]))) or\r\n    (exists r[\"building\"] and contains(set: ${BATIMENT:json}, value: strings.toLower(v: r[\"building\"]))))\r\n  |> filter(fn: (r) => (exists r[\"salle\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"salle\"]))) or\r\n    (exists r[\"room\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"room\"]))))\r\n  |> keep(columns: [\"_value\", \"_time\", \"batiment\", \"salle\", \"site\"])  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n"
    },
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"iot-platform\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${MEASUREMENT}\" and \"${MEASUREMENT}\" == \"Co2_SHT\")\r\n  |> filter(fn: (r) => exists r[\"site\"] and contains(set: ${CAMPUS:json}, value: strings.toLower(v: r[\"site\"])))\r\n  |> filter(fn: (r) => (exists r[\"batiment\"] and contains(set: ${BATIMENT:json}, value: strings.toLower(v: r[\"batiment\"]))) or\r\n    (exists r[\"building\"] and contains(set: ${BATIMENT:json}, value: strings.toLower(v: r[\"building\"]))))\r\n  |> filter(fn: (r) => (exists r[\"salle\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"salle\"]))) or\r\n    (exists r[\"room\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"room\"]))))\r\n  |> keep(columns: [\"_value\", \"_time\", \"batiment\", \"salle\", \"site\"])  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Single View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "${MEASUREMENT} of ${ROOM}",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "repeat": "ROOM",
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nmeasurement = strings.split(v: \"${MEASUREMENT}\", t: \" \")[0]\r\n\r\nfrom(bucket: \"iot-platform\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"value\")\r\n|> filter(fn: (r) => r[\"_field\"] == measurement and measurement == \"TempC_SHT\")\r\n|> filter(fn: (r) => exists r[\"site\"] and contains(value: strings.toLower(v: r.site), set: ${CAMPUS:json}))\r\n|> filter(fn: (r) => exists r[\"batiment\"] and contains(value: strings.toLower(v: r.batiment), set: ${BATIMENT:json}))\r\n|> filter(fn: (r) => exists r[\"salle\"] and (strings.toLower(v: r.salle) == \"${ROOM}\"))\r\n|> keep(columns: [\"_value\", \"_time\", \"batiment\", \"salle\", \"site\"])|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"${MEASUREMENT}\")\r\n"
      },
      {
       "query": "import \"strings\"\r\n\r\nmeasurement = strings.split(v: \"${MEASUREMENT}\", t: \" \")[0]\r\n\r\nfrom(bucket: \"iot-platform\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"value\")\r\n|> filter(fn: (r) => r[\"_field\"] == measurement and measurement == \"Hum_SHT\")\r\n|> filter(fn: (r) => exists r[\"site\"] and contains(value: strings.toLower(v: r.site), set: ${CAMPUS:json}))\r\n|> filter(fn: (r) => exists r[\"batiment\"] and contains(value: strings.toLower(v: r.batiment), set: ${BATIMENT:json}))\r\n|> filter(fn: (r) => exists r[\"salle\"] and (strings.toLower(v: r.salle) == \"${ROOM}\"))\r\n|> keep(columns: [\"_value\", \"_time\", \"batiment\", \"salle\", \"site\"])|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"${MEASUREMENT}\")\r\n"
      },
      {
       "query": "import \"strings\"\r\n\r\nmeasurement = strings.split(v: \"${MEASUREMENT}\", t: \" \")[0]\r\n\r\nfrom(bucket: \"iot-platform\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"value\")\r\n|> filter(fn: (r) => r[\"_field\"] == measurement and measurement == \"Co2_SHT\")\r\n|> filter(fn: (r) => exists r[\"site\"] and contains(value: strings.toLower(v: r.site), set: ${CAMPUS:json}))\r\n|> filter(fn: (r) => exists r[\"batiment\"] and contains(value: strings.toLower(v: r.batiment), set: ${BATIMENT:json}))\r\n|> filter(fn: (r) => exists r[\"salle\"] and (strings.toLower(v: r.salle) == \"${ROOM}\"))\r\n|> keep(columns: [\"_value\", \"_time\", \"batiment\", \"salle\", \"site\"])|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"${MEASUREMENT}\")\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Advanced Visualisations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "RSSI",
     "type": "timeseries",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "query": "import \"strings\"\n\nfrom(bucket: \"iot-platform\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rssi\")\n  |> filter(fn: (r) => exists r[\"site\"] and contains(set: ${CAMPUS:json}, value: strings.toLower(v: r[\"site\"])))\n  |> filter(fn: (r) => (exists r[\"batiment\"] and contains(set: ${BATIMENT:json}, value: strings.toLower(v: r[\"batiment\"]))) or\n    (exists r[\"building\"] and contains(set: ${BATIMENT:json}, value: strings.toLower(v: r[\"building\"]))))\n  |> filter(fn: (r) => (exists r[\"salle\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"salle\"]))) or\n    (exists r[\"room\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"room\"]))))\n  |> keep(columns: [\"_value\", \"_time\", \"_field\", \"batiment\", \"salle\", \"site\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
      }
     ]
    },
    {
     "title": "SNR",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "query": "import \"strings\"\n\nfrom(bucket: \"iot-platform\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\n  |> filter(fn: (r) => exists r[\"site\"] and contains(set: ${CAMPUS:json}, value: strings.toLower(v: r[\"site\"])))\n  |> filter(fn: (r) => (exists r[\"batiment\"] and contains(set: ${BATIMENT:json}, value: strings.toLower(v: r[\"batiment\"]))) or (exists r[\"building\"] and contains(set: ${BATIMENT:json}, value: strings.toLower(v: r[\"building\"]))))\n  |> filter(fn: (r) => (exists r[\"salle\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"salle\"]))) or (exists r[\"room\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"room\"]))))\n  |> keep(columns: [\"_value\", \"_time\", \"_field\", \"batiment\", \"salle\", \"site\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
      }
     ]
    },
    {
     "title": "Spreading Factor",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
     "targets": [
      {
       "query": "import \"strings\"\n\nfrom(bucket: \"iot-platform\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"modulation_lora_spreadingFactor\")\n  |> filter(fn: (r) => exists r[\"site\"] and contains(set: ${CAMPUS:json}, value: strings.toLower(v: r[\"site\"])))\n  |> filter(fn: (r) => (exists r[\"batiment\"] and contains(set: ${BATIMENT:json}, value: strings.toLower(v: r[\"batiment\"]))) or (exists r[\"building\"] and contains(set: ${BATIMENT:json}, value: strings.toLower(v: r[\"building\"]))))\n  |> filter(fn: (r) => (exists r[\"salle\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"salle\"]))) or (exists r[\"room\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"room\"]))))\n  |> keep(columns: [\"_value\", \"_time\", \"_field\", \"batiment\", \"salle\", \"site\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
      }
     ]
    }
   ]
  }
 ]
}