{
 "title": "Patrimoine_Multi_Display_Tag",
 "description": "The temperatures and humidity of all technolac campus' rooms, caught by a LHT65 sensor.",
 "tags": [
  "Patrimoine",
  "LHT65"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "MEASUREMENT",
    "query": "Temperature : TempC_SHT, Relative Humidity : Hum_SHT"
   },
   {
    "name": "SITE",
    "query": "import \"influxdata/influxdb/schema\"\r\nimport \"strings\"\r\nimport \"array\"\r\n \r\nsites = schema.tagValues(\r\n  bucket: \"Temperature room USMB\",\r\n  tag: \"site\",\r\n  predicate: (r) => r._field == \"rssi\"\r\n    and r.applicationName == \"Temperature room USMB\"\r\n    and exists r[\"site\"],\r\n  start: v.timeRangeStart\r\n)\r\n|> map(fn: (r) => ({ r with site: strings.toLower(v: r._value) }))\r\n|> distinct(column: \"site\")\r\n\r\ndefault = array.from(rows: [{\"_value\": \"none\"}])\r\n\r\nunion(tables: [sites, default])\r\n"
   },
   {
    "name": "BUILDING",
    "query": "import \"influxdata/influxdb/schema\"\r\nimport \"strings\"\r\nimport \"array\"\r\n\r\nfrench = schema.tagValues(\r\n  bucket: \"Temperature room USMB\",\r\n  predicate: (r) => r._field == \"rssi\"\r\n    and exists r[\"site\"]\r\n    and exists r[\"batiment\"] \r\n    and contains(value: strings.toLower(v:r[\"site\"]), set: ${SITE:json}),\r\n  tag: \"batiment\",\r\n  start: v.timeRangeStart\r\n)\r\n|> map(fn: (r) => ({ r with building: strings.toLower(v: r._value) }))\r\n|> distinct(column: \"building\")\r\n\r\ndefault = array.from(rows: [{\"_value\": \"none\"}])\r\n\r\nunion(tables: [french, default])"
   },
   {
    "name": "ROOM",
    "query": "import \"influxdata/influxdb/schema\"\r\nimport \"strings\"\r\nimport \"array\"\r\n \r\nfrench = schema.tagValues(\r\n  bucket: \"Temperature room USMB\",\r\n  predicate: (r) => \r\n    r._field == \"rssi\"\r\n    and exists r[\"site\"]\r\n    and exists r[\"batiment\"]\r\n    and exists r[\"salle\"]\r\n    and contains(value: strings.toLower(v: r[\"site\"]), set: ${SITE:json}) \r\n    and contains(value: strings.toLower(v: r[\"batiment\"]), set: ${BUILDING:json}),\r\n  tag: \"salle\",\r\n  start: v.timeRangeStart\r\n)\r\n|> map(fn: (r) => ({ r with room: strings.toLower(v: r._value) }))\r\n|> group(columns: [\"room\"])\r\n|> distinct(column: \"room\")\r\n\r\ndefault = array.from(rows: [{\"_value\": \"none\"}])\r\n\r\nunion(tables: [french, default])\r\n"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Temperature and Humidity at Technolac\r\nThe temperatures and humidity of all Technolac campus' rooms, caught by a LHT65 sensor.\r\n"
   }
  },
  {
   "title": "${MEASUREMENT} of ${ROOM}",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 3 },
   "repeat": "MEASUREMENT",
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"Temperature room USMB\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${MEASUREMENT}\" and \"${MEASUREMENT}\" == \"TempC_SHT\")\r\n  |> filter(fn: (r) => exists r[\"site\"] and contains(set: ${SITE:json}, value: strings.toLower(v: r[\"site\"])))\r\n  |> filter(fn: (r) => (exists r[\"batiment\"] and contains(set: ${BUILDING:json}, value: strings.toLower(v: r[\"batiment\"]))) or\r\n    (exists r[\"building\"] and contains(set: ${BUILDING:json}, value: strings.toLower(v: r[\"building\"]))))\r\n  |> filter(fn: (r) => (exists r[\"salle\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"salle\"]))) or\r\n    (exists r[\"room\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"room\"]))))\r\n  |> drop(columns: [\"host\", \"applicationName\", \"devEui\", \"deviceName\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group(columns: []) // Or union\r\n  |> sort(columns: [\"salle\"], desc: false)\r\n  |> group(columns: [\"salle\", \"batiment\", \"site\"])\r\n"
    },
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"Temperature room USMB\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${MEASUREMENT}\" and \"${MEASUREMENT}\" == \"Hum_SHT\")\r\n  |> filter(fn: (r) => exists r[\"site\"] and contains(set: ${SITE:json}, value: strings.toLower(v: r[\"site\"])))\r\n  |> filter(fn: (r) => (exists r[\"batiment\"] and contains(set: ${BUILDING:json}, value: strings.toLower(v: r[\"batiment\"]))) or\r\n    (exists r[\"building\"] and contains(set: ${BUILDING:json}, value: strings.toLower(v: r[\"building\"]))))\r\n  |> filter(fn: (r) => (exists r[\"salle\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"salle\"]))) or\r\n    (exists r[\"room\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"room\"]))))\r\n  |> drop(columns: [\"host\", \"applicationName\", \"devEui\", \"deviceName\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group(columns: []) // Or union\r\n  |> sort(columns: [\"salle\"], desc: false)\r\n  |> group(columns: [\"salle\", \"batiment\", \"site\"])\r\n"
    }
   ]
  },
  {
   "title": "Single-View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "${MEASUREMENT} of ${ROOM}",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "repeat": "ROOM",
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nmeasurement = strings.split(v: \"${MEASUREMENT}\", t: \" \")[0]\r\n\r\nfrom(bucket: \"Temperature room USMB\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == measurement and measurement == \"TempC_SHT\")\r\n  |> filter(fn: (r) => exists r[\"salle\"] and (strings.toLower(v: r.salle) == \"${ROOM}\"))\r\n  |> drop(columns: [\"host\", \"applicationName\", \"devEui\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"${MEASUREMENT}\")\r\n"
      },
      {
       "query": "import \"strings\"\r\n\r\nmeasurement = strings.split(v: \"${MEASUREMENT}\", t: \" \")[0]\r\n\r\nfrom(bucket: \"Temperature room USMB\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == measurement and measurement == \"Hum_SHT\")\r\n  |> filter(fn: (r) => exists r[\"salle\"] and (strings.toLower(v: r.salle) == \"${ROOM}\"))\r\n  |> drop(columns: [\"host\", \"applicationName\", \"devEui\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"${MEASUREMENT}\")\r\n"
      }
     ]
    }
   ]
  },
  { "title": "Advanced visualisation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"Temperature room USMB\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rssi\")\r\n  |> filter(fn: (r) => exists r[\"site\"] and contains(set: ${SITE:json}, value: strings.toLower(v: r[\"site\"])))\r\n  |> filter(fn: (r) => (exists r[\"batiment\"] and contains(set: ${BUILDING:json}, value: strings.toLower(v: r[\"batiment\"]))) or\r\n    (exists r[\"building\"] and contains(set: ${BUILDING:json}, value: strings.toLower(v: r[\"building\"]))))\r\n  |> filter(fn: (r) => (exists r[\"salle\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"salle\"]))) or\r\n    (exists r[\"room\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"room\"]))))\r\n\r\n  |> drop(columns: [\"host\", \"gatewayId\", \"applicationName\", \"devEui\", \"deviceName\"])\r\n  |> map(fn: (r) => ({ r with type: \"RSSI\" }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "SNR",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"Temperature room USMB\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => exists r[\"site\"] and contains(set: ${SITE:json}, value: strings.toLower(v: r[\"site\"])))\r\n  |> filter(fn: (r) => (exists r[\"batiment\"] and contains(set: ${BUILDING:json}, value: strings.toLower(v: r[\"batiment\"]))) or\r\n    (exists r[\"building\"] and contains(set: ${BUILDING:json}, value: strings.toLower(v: r[\"building\"]))))\r\n  |> filter(fn: (r) => (exists r[\"salle\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"salle\"]))) or\r\n    (exists r[\"room\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"room\"]))))\r\n\r\n  |> drop(columns: [\"host\", \"gatewayId\", \"applicationName\", \"devEui\", \"deviceName\"])\r\n  |> map(fn: (r) => ({ r with type: \"RSSI\" }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Spreading Factor",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"Temperature room USMB\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"modulation_lora_spreadingFactor\")\r\n  |> filter(fn: (r) => exists r[\"site\"] and contains(set: ${SITE:json}, value: strings.toLower(v: r[\"site\"])))\r\n  |> filter(fn: (r) => (exists r[\"batiment\"] and contains(set: ${BUILDING:json}, value: strings.toLower(v: r[\"batiment\"]))) or\r\n    (exists r[\"building\"] and contains(set: ${BUILDING:json}, value: strings.toLower(v: r[\"building\"]))))\r\n  |> filter(fn: (r) => (exists r[\"salle\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"salle\"]))) or\r\n    (exists r[\"room\"] and contains(set: ${ROOM:json}, value: strings.toLower(v: r[\"room\"]))))\r\n\r\n  |> drop(columns: [\"host\", \"gatewayId\", \"applicationName\", \"devEui\", \"deviceName\"])\r\n  |> map(fn: (r) => ({ r with type: \"RSSI\" }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}